# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVckOumObaFP3Q3hZSgyxHYzH_b5-6sL
"""

#   Codigo que implementa un esquema numerico
#   para determinar la precision de una maquina
#
#           Autor:
#   Angel Gabriel Chim Vera
#   angchimvera@gmail.com
#   Version 1.0 : 04/02/2025
#

import numpy as np  # Se importa la biblioteca numpy para realizar cálculos numéricos

# Se inicializa epsilon en 1.0. Esta variable representa el valor que se prueba
# para encontrar la precisión de la máquina en punto flotante.
epsilon = 1.0
iteracion = 0  # Contador de iteraciones

# Bucle para encontrar la menor cantidad de epsilon que afecta la suma con 1.0
while 1.0 + epsilon != 1.0:
    epsilon /= 2  # Se divide epsilon entre 2 en cada iteración
    iteracion += 1  # Se incrementa el contador de iteraciones
    print(f"Iteración: {iteracion}, Precisión de máquina: {epsilon}")

# Como la última iteración rompió la condición, se multiplica epsilon por 2
# para recuperar el último valor que sí afectaba la suma con 1.0
epsilon *= 2

# Se imprime el valor final de la precisión de la máquina
print(f"Precisión de máquina: {epsilon}")